/**
 * Skill name (as written in PROFILE_DATA) → simple-icons slug.
 * Skills that are not listed here have no logo and render as a text chip.
 * The SVG for each slug lives in public/logos/skills/, generated by
 * `npm run generate:skill-logos`.
 */
export const SKILL_LOGOS: Readonly<Record<string, string>> = {
  TypeScript: 'typescript',
  JavaScript: 'javascript',
  Python: 'python',
  'Node.js': 'nodedotjs',
  NestJS: 'nestjs',
  Express: 'express',
  PostgreSQL: 'postgresql',
  Redis: 'redis',
  MongoDB: 'mongodb',
  MySQL: 'mysql',
  Angular: 'angular',
  React: 'react',
  'Next.js': 'nextdotjs',
  'Tailwind CSS': 'tailwindcss',
  HTML5: 'html5',
  CSS3: 'css3',
  NGXS: 'ngxs',
  'Django REST Framework': 'djangorest',
  Docker: 'docker',
  Kubernetes: 'kubernetes',
  'GitLab CI': 'gitlab',
  'GitHub Actions': 'githubactions',
  Prometheus: 'prometheus',
  Grafana: 'grafana',
  Git: 'git',
  Jest: 'jest',
  Cypress: 'cypress',
  pytest: 'pytest',
  'Claude Code': 'claude',
  'GitHub Copilot': 'githubcopilot',
  Java: 'java',
  'C++': 'cplusplus',
  'C#': 'csharp',
  Unity: 'unity',
  SQLite: 'sqlite',
  Arduino: 'arduino',
};

/**
 * Slugs simple-icons does not ship (Java and C# were removed for trademark
 * reasons; CSS3, NGXS and Django REST Framework were never included). Their
 * SVGs are committed by hand — from devicon (DRF with its construction lines
 * removed and cropped), or for NGXS the official PNG made transparent and
 * wrapped in an SVG — and the generator script skips them.
 */
export const CUSTOM_LOGO_SLUGS: ReadonlySet<string> = new Set(['java', 'csharp', 'css3', 'ngxs', 'djangorest']);

export function skillLogoSrc(skill: string): string | null {
  const slug = SKILL_LOGOS[skill];
  return slug ? `logos/skills/${slug}.svg` : null;
}
