/**
 * Skill name (as written in PROFILE_DATA) → simple-icons slug.
 * Skills that are not listed here have no logo and render as a text chip.
 * The SVG for each slug lives in public/logos/skills/, generated by
 * `npm run generate:skill-logos`.
 */
export const SKILL_LOGOS: Readonly<Record<string, string>> = {
  TypeScript: 'typescript',
  JavaScript: 'javascript',
  Python: 'python',
  'Node.js': 'nodedotjs',
  NestJS: 'nestjs',
  Express: 'express',
  PostgreSQL: 'postgresql',
  Redis: 'redis',
  MongoDB: 'mongodb',
  MySQL: 'mysql',
  Angular: 'angular',
  React: 'react',
  'Next.js': 'nextdotjs',
  'Tailwind CSS': 'tailwindcss',
  HTML5: 'html5',
  Docker: 'docker',
  Kubernetes: 'kubernetes',
  'GitLab CI': 'gitlab',
  'GitHub Actions': 'githubactions',
  Prometheus: 'prometheus',
  Grafana: 'grafana',
  Git: 'git',
  Jest: 'jest',
  Cypress: 'cypress',
  pytest: 'pytest',
  'Claude Code': 'claude',
  'GitHub Copilot': 'githubcopilot',
};
